name: Workflow with manual trigger and Environment Variables

on:
  workflow_dispatch: # Manual trigger
env:
  WORKFLOW_ENV_VARIABLE: "Workflow Level"

jobs:
  example_job:
    runs-on: ubuntu-latest
    env:
      JOB_ENV_VARIABLE: "Job Level"

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Print Environment Variables
      run: |
        echo "Workflow Level Environment Variable: $WORKFLOW_ENV_VARIABLE"
        echo "Job Level Environment Variable: $JOB_ENV_VARIABLE"
        echo "Step Level Environment Variable: ${{ env.STEP_ENV_VARIABLE }}"
      env:
        STEP_ENV_VARIABLE: "Step Level"