name: Dependent Jobs Example

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    needs: [setup]  # Build job depends on setup job

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build
        run: |
          echo "build commands"
          echo " build completed"
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: some random commands
        run: echo "setup done"

  test:
    runs-on: ubuntu-latest
    needs: build  # The 'test' job depends on the 'build' job

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Tests
        run: |
          echo " test commands"
          echo " test completed"